# Generated by Django 2.2.2 on 2019-06-08 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_private', models.BooleanField(default=False)),
                ('location_latitude', models.FloatField()),
                ('location_longitude', models.FloatField()),
                ('qrcode_advertising', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_post', models.FileField(upload_to='videos/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=False)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_viewed', models.DateTimeField()),
                ('duration_viewed', models.TimeField()),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Post')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(max_length=13)),
                ('profile_pic', models.ImageField(null=True, upload_to='profile_pic_folder/')),
                ('date_birth', models.DateField(null=True)),
                ('street_address', models.CharField(max_length=100)),
                ('number_address', models.CharField(max_length=7)),
                ('city_address', models.CharField(max_length=100)),
                ('zipcode_address', models.CharField(max_length=9)),
                ('district_address', models.CharField(max_length=100)),
                ('complement_address', models.CharField(max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Event')),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Post')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('body_comment', models.TextField()),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Post')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start_follow', models.DateTimeField(auto_now_add=True)),
                ('id_follower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='who_follows', to=settings.AUTH_USER_MODEL)),
                ('id_following', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='who_is_followed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='id_type_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.TypeEvent'),
        ),
        migrations.AddField(
            model_name='event',
            name='id_user_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
