# Generated by Django 2.2.2 on 2019-06-10 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_can_view', models.PositiveIntegerField()),
                ('who_can_post', models.PositiveIntegerField()),
                ('who_can_interact', models.PositiveIntegerField()),
                ('who_can_invite', models.PositiveIntegerField()),
                ('id_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Event')),
            ],
        ),
    ]
