# Generated by Django 2.2.2 on 2019-06-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_configevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='talent_program',
            field=models.BooleanField(default=False),
        ),
    ]
